### ISSUE TITLE
Board games

### ISSUE THREAD

**Issue by whitneyfirth** [whitneyburton/gameflix#4]
When a user clicks on board games, they should see a list of only board games.
- [x] - Create button/div that will have text the text `Board Games`
- [x] - should have event listener for this button
- [x] - should be able to see only board games when button is clicked
- [x] - should give visual that the button was clicked(like a highlight)
- [x] - should be able to see card games and board games if clicked twice
- [x] - should remove highlight(or other indication) upon second click

**Comment by JustinD85** [comment]
- [ ] - Create button/div that will have text the text `Board Games`
- [ ] - should have event listener for this button
- [ ] - should be able to see only board games when button is clicked
- [ ] - should give visual that the button was clicked(like a highlight)
- [ ] - should be able to see card games and board games if clicked twice
- [ ] - should remove highlight(or other indication) upon second click
