### ISSUE TITLE
Card games

### ISSUE THREAD

**Issue by whitneyfirth** [whitneyburton/gameflix#5]
When a user clicks on card games, they should a see a list of only card games.
- [x] - Create button/div that will have text the text `Card Games`
- [x] - should have event listener for this button
- [x] - should be able to see only card games when button is clicked
- [x] - should give visual that the button was clicked(like a highlight)
- [x] - should be able to see card games and board games if clicked twice
- [x] - should remove highlight(or other indication) upon second click

**Comment by JustinD85** [comment]
- [ ] - Create button/div that will have text the text `Card Games`
- [ ] - should have event listener for this button
- [ ] - should be able to see only card games when button is clicked
- [ ] - should give visual that the button was clicked(like a highlight)
- [ ] - should be able to see card games and board games if clicked twice
- [ ] - should remove highlight(or other indication) upon second click
